[book]
#language = "en"
#src = "src"
src = "book"
title = "Makesure Manual"

[build]
build-dir = "build"

[output.html]
git-repository-url = "https://github.com/xonixx/makesure"
#site-url = "/"

#[output.linkcheck]