#!/bin/sh

set -eu

MYDIR=$(
  cd "$(dirname "$0")"
  pwd
)

AWK_CMD="$1"
shift
SEP="$1"
shift

if [ $SEP != '--' ]
then
  echo 'missing SEP' >&2
  exit 2
fi

case "$AWK_CMD" in
  '' | awk)
    MAKESURE_AWK="/usr/bin/awk"
    ;;
  /* | 'java '*)
    MAKESURE_AWK="$AWK_CMD"
    ;;
  *:cover)
    AWK_CMD="${AWK_CMD%:cover}" # trim the `:cover` suffix to identify goawk exe
    MAKESURE_AWK="$MYDIR/soft/${AWK_CMD} -covermode=set -coverprofile=/tmp/cov.txt -coverappend"
    ;;
  *)
    MAKESURE_AWK="$MYDIR/soft/${AWK_CMD}"
    ;;
esac

case "$MAKESURE_AWK" in
  *gawk*)
    export AWKLIBPATH="$MYDIR/soft/${AWK_CMD}_libs"
    exec $MAKESURE_AWK -v "Version=$NEXT_VERSION" -v "Prog=$0" -v Gawk=1 -l time \
      -f "$MYDIR/dbg.awk" -f "$MYDIR/makesure.awk" Makesurefile "$@"
    ;;
  *)
    exec $MAKESURE_AWK -v "Version=$NEXT_VERSION" -v "Prog=$0" -f "$MYDIR/mawk_ext.awk" \
      -f "$MYDIR/dbg.awk" -f "$MYDIR/makesure.awk" Makesurefile "$@"
    ;;
esac
