#!/bin/sh

set -eu

MYDIR=$(
  cd "$(dirname "$0")"
  pwd
)

VER='0.0.0' # hardcode for dev

# makesure_dev can be called in two ways
# - `makesure_dev AWK_CMD -- MAKESURE_PARAMS`
# - `makesure_dev MAKESURE_PARAMS` - to be compatible with @calls invocation

AWK_CMD=''
if [ "${2-}" = '--' ]
then
  AWK_CMD="$1"
  shift 2
fi

case "$AWK_CMD" in
  '' | awk)
    MAKESURE_AWK="/usr/bin/awk"
    ;;
  /* | 'java '*)
    MAKESURE_AWK="$AWK_CMD"
    ;;
  *:cover)
    AWK_CMD="${AWK_CMD%:cover}" # trim the `:cover` suffix to identify goawk exe
    MAKESURE_AWK="$MYDIR/soft/${AWK_CMD} -covermode=set -coverprofile=/tmp/cov.txt -coverappend"
    ;;
  *)
    MAKESURE_AWK="$MYDIR/soft/${AWK_CMD}"
    ;;
esac

case "$MAKESURE_AWK" in
  *gawk*)
    export AWKLIBPATH="$MYDIR/soft/${AWK_CMD}_libs"
    exec $MAKESURE_AWK -v "Version=$VER" -v "Prog=$0" -v Gawk=1 -l time \
      -f "$MYDIR/dbg.awk" -f "$MYDIR/makesure.awk" Makesurefile "$@"
    ;;
  *)
    exec $MAKESURE_AWK -v "Version=$VER" -v "Prog=$0" -f "$MYDIR/mawk_ext.awk" \
      -f "$MYDIR/dbg.awk" -f "$MYDIR/makesure.awk" Makesurefile "$@"
    ;;
esac
