#!/bin/sh

mydir=$(
  cd "$(dirname "$0")"
  pwd
)

exec /home/xonix/proj/goawk/goawk \
  -covermode=set \
  -coverprofile="/tmp/cov.txt" \
  -v "Version=$NEXT_VERSION" -v "Prog=$0" -f "$mydir/mawk_ext.awk" -f "$mydir/makesure.awk" Makesurefile "$@"

